### ISSUE TITLE
Timed out waiting for EnginePeerStateUpdatedEvent

### ISSUE THREAD

**Issue by rishu2004** [livekit/client-sdk-flutter#410] opened 2023-11-25 16:53 UTC
I encountered an error with the latest package on Windows. The error message is Timed out waiting for EnginePeerStateUpdatedEvent. The package causing the issue is livekit_client: ^1.5.3 Can you provide assistance or suggestions on how to resolve this issue?

ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LiveKit Exception: [ConnectException] Timed out waiting for EnginePeerStateUpdatedEvent
#0      Engine.connect.<anonymous closure>
engine.dart:168
#1      _RootZone.run (dart:async/zone.dart:1655:54)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:882:34)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

**Comment by davidzhao** [comment] 2023-11-26 00:05
dupe of #409

**Closed by davidzhao** 2023-11-26 00:05 UTC
