### ISSUE TITLE
improve sound quality when calling 

### ISSUE THREAD

**Issue by thaidmfinnick** [livekit/client-sdk-flutter#317] opened 2023-07-10 08:43 UTC
Hello guys and @cloudwebrtc,
I'm currently working on project using Livekit to do voice call and audio call. Logic is fine but I have problem relevant to sound quality when calling. When I call, I can hear the sound of typing, echos, noise very far from me. I have using roomOptions in docs, but it seems doesn't work at all. 

` defaultAudioCaptureOptions: AudioCaptureOptions(
        deviceId: '',
        noiseSuppression: true,
        echoCancellation: true,
        autoGainControl: true,
        highPassFilter: true,
        typingNoiseDetection: true)
`
This is the video I record: (I call from Windows to MacOS, if I call from mobile to desktop same problem is happened)

https://github.com/livekit/client-sdk-flutter/assets/83997264/96f78dd6-bbdf-45cd-a843-16aa6ea2dce7

I have searched in documentation and issues on github and try many ways but the problem is still there. How can I improve this sound quality? Thank you!

My Flutter configuration:
- Flutter version: 3.7.9 (channel stable)
- Livekit Client: 1.3.1

**Comment by davidzhao** [comment] 2023-07-14 20:32
@thaidmfinnick can you reproduce this with the built-in example app? 

what about trying to use meet.livekit.io on the same device?

**Comment by cloudwebrtc** [comment] 2023-07-14 23:59
This seems to be due to the built-in NS algorithm on the desktop side not fully canceling keyboard taps or external noise (we may also need a third-party NS library to optimize noise reduction), especially when using speakers and high-sensitivity microphones.

This kind of twittering sound also usually occurs when two mobile devices speakerphones are turned on at the same time to make a phone calls, and the NS and AEC algorithms are not perfect.

**Comment by thaidmfinnick** [comment] 2023-07-17 01:57
Thanks for your responses! I have tried with meet.livekit.io @davidzhao, and here is the result, it's the same sound noise like my app. 

https://github.com/livekit/client-sdk-flutter/assets/83997264/a8774fef-defc-4c6e-8d33-7ded4bbda518

**Comment by thaidmfinnick** [comment] 2023-07-17 02:05
@cloudwebrtc You mean that the algorithms cannot work as expected because of desktop side and from now, we cannot deal to this desktop's problem, can you?

**Comment by davidzhao** [comment] 2023-07-22 21:14
This is the expected behavior of WebRTC noise cancellation. Google Meet is using a proprietary system that appears to be doing a better job here.

There isn't much we could do at this point. Closing the issue

**Closed by davidzhao** 2023-07-22 21:14 UTC
