### ISSUE TITLE
UI Freeze on Reconnect with enableVisualizer: true in LiveKit Flutter Plugin

### ISSUE THREAD

**Issue by ChungangL** [livekit/client-sdk-flutter#659] opened 2024-12-17 03:14 UTC
Description:
When using the LiveKit Flutter plugin with the enableVisualizer parameter set to true, the application freezes after disconnecting and reconnecting during an AI agent voice call. The issue is specifically triggered when the room is reconnected after a disconnect, causing the UI to lock and fail to recover.

Steps to Reproduce:

Set enableVisualizer: true in the room options.
Use the following connection code to join a room:
void _onTapConnect() async{
  const roomOptions = RoomOptions(enableVisualizer: true);
  _room = Room(roomOptions: roomOptions);
  await _room!.connect(Info.liveKitWsUrl, _token.value!);
  await _room!.localParticipant?.setMicrophoneEnabled(true);
}
After successfully connecting, disconnect the room using the following:
void _reconnect() async {
  await _room?.disconnect();
  await _room?.dispose();
  _requestToken(resume: true);
  _onTapConnect();
}
Reconnect the room and observe the UI freeze.
Expected Behavior:
The room should reconnect without freezing the UI.

Actual Behavior:
After disconnecting and attempting to reconnect, the UI becomes unresponsive and freezes.

Error Log:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LiveKit Exception: [MediaConnectException] Timed out waiting for PeerConnection to connect, please check your network for ice connectivity
#0      Engine.connect.<anonymous closure> (package:livekit_client/src/core/engine.dart:213:26)
#1      _RootZone.run (dart:async/zone.dart:1655:54)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:943:34)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Additional Information:

The issue only occurs when enableVisualizer is set to true.
The error log indicates a timeout during the PeerConnection connection phase, which could suggest network issues or problems with ICE connectivity.
The problem results in the UI becoming unresponsive and unable to recover until the app is restarted.
Possible Solution/Workaround:
It would be helpful to investigate any changes in the handling of visualizer-related resources during disconnections or reconnections. Ensuring that all resources are properly released and re-initialized on reconnection could help resolve the issue.

Environment:

Flutter version: 3.22.1
LiveKit Flutter plugin version: 2.3.2
Device: iPhone 12
OS: iOS

**Comment by ChungangL** [comment] 2024-12-24 09:03
Hi @cloudwebrtc
First of all, thank you for the fix, but I tried version 2.3.3, and the issue still persists.

**Comment by cloudwebrtc** [comment] 2024-12-24 23:56
Hi @ChungangL , I guess it should be that `MediaConnectException` still exists when repeatedly connecting, but the Visualizer should not block the UI because I fixed a related issue

**Comment by ChungangL** [comment] 2024-12-25 06:11
Hi @cloudwebrtc, Thank you for your great work on this project. I encountered an issue while using the LiveKit plugin in my Flutter app.

I am connecting to my custom AI agent server, and everything works fine on Android. However, when testing on iOS, I observed the following behavior:

When enableVisualizer is set to true:

The app screen completely freezes after reconnecting.
Occasionally, the console logs an error: MediaConnectException.
I'm not certain whether the screen freeze is related to this error.
When enableVisualizer is set to false:

Everything works fine on iOS.
I suspect that the enableVisualizer setting might be causing the UI freeze issue on iOS.

Here is my test code:
`class LiveKitTestPage extends StatefulWidget {
  final UserModel bot;
  const LiveKitTestPage({super.key, required this.bot});

  @override
  State<LiveKitTestPage> createState() => _LiveKitTestPageState();
}

class _LiveKitTestPageState extends State<LiveKitTestPage> {

  String _callId = "";

  final RxnString _token = RxnString();

  Room? _room;

  Timer? _timer;

  final RxInt _seconds = 0.obs;

  @override
  void initState() {
    super.initState();
    _callId = const Uuid().v4();
    _requestToken();
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      _seconds.value++;
    });
  }

  @override
  void dispose() {
    _disconnect();
    _timer?.cancel();
    super.dispose();
  }

  Future<void> _requestToken({bool resume = false}) async{
    final resultData = await apiManager.getCallRoomOptions(
        botId: widget.bot.userId,
        voiceId: widget.bot.voiceId,
        callId: _callId,
        resumeCall: resume
    );
    if (resultData.result) {
      _token.value = resultData.data["token"];
    }
  }

  void _connect() async{
    _room = Room(roomOptions: RoomOptions(enableVisualizer: true, adaptiveStream: true, dynacast: true));
    await _room!.connect(Info.liveKitWsUrl, _token.value!);
    await _room!.localParticipant?.setMicrophoneEnabled(true);
  }

  Future<void> _disconnect() async{
    await _room?.disconnect();
    await _room?.dispose();
  }

  Future<void> _reconnect() async {
    await _disconnect();
    await _requestToken(resume: true);
    _connect();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: _mainView(),
    );
  }

  Widget _mainView() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Obx(() {
            return Text(
              "${_seconds.value.toString()}s",
              style: Styles.textStyleSemiBold(30),
            );
          }),
          const SizedBox(height: 100),
          Obx(() {
            if (_token.value?.isNotEmpty == true) {
              return GestureContainer(
                onTap: () {
                  showTipsToast("on tap connect");
                  _connect();
                },
                color: Colors.greenAccent,
                child: Text(
                  "connect",
                  style: Styles.textStyleMedium(30),
                ),
              );
            }
            return const LoadingView();
          }),
          const SizedBox(height: 100),
          GestureContainer(
            onTap: () {
              showTipsToast("on tap reconnect");
              _reconnect();
            },
            color: Colors.greenAccent,
            child: Text(
              "reconnect",
              style: Styles.textStyleMedium(30),
            ),
          )
        ],
      ),
    );
  }
}`

Uploading RPReplay_Final1735098560.MP4…

If there are any suggestions or workarounds to address this issue, I would appreciate your guidance.

**Comment by ChungangL** [comment] 2024-12-25 06:27
@cloudwebrtc ,Thank you for your great work on this project. I encountered an issue while using the LiveKit plugin in my Flutter app.

I am connecting to my custom AI agent server, and everything works fine on Android. However, when testing on iOS, I observed the following behavior:

When enableVisualizer is set to true:

The app screen completely freezes after reconnecting.
Occasionally, the console logs an error: MediaConnectException.
I'm not certain whether the screen freeze is related to this error.
When enableVisualizer is set to false:

Everything works fine on iOS.
I suspect that the enableVisualizer setting might be causing the UI freeze issue on iOS.

Herr is my test code:
```
class LiveKitTestPage extends StatefulWidget {
  final UserModel bot;
  const LiveKitTestPage({super.key, required this.bot});

  @override
  State<LiveKitTestPage> createState() => _LiveKitTestPageState();
}

class _LiveKitTestPageState extends State<LiveKitTestPage> {

  String _callId = "";

  final RxnString _token = RxnString();

  Room? _room;

  Timer? _timer;

  final RxInt _seconds = 0.obs;

  @override
  void initState() {
    super.initState();
    _callId = const Uuid().v4();
    _requestToken();
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      _seconds.value++;
    });
  }

  @override
  void dispose() {
    _disconnect();
    _timer?.cancel();
    super.dispose();
  }

  Future<void> _requestToken({bool resume = false}) async{
    final resultData = await apiManager.getCallRoomOptions(
        botId: widget.bot.userId,
        voiceId: widget.bot.voiceId,
        callId: _callId,
        resumeCall: resume
    );
    if (resultData.result) {
      _token.value = resultData.data["token"];
    }
  }

  void _connect() async{
    _room = Room(roomOptions: RoomOptions(enableVisualizer: true, adaptiveStream: true, dynacast: true));
    await _room!.connect(Info.liveKitWsUrl, _token.value!);
    await _room!.localParticipant?.setMicrophoneEnabled(true);
  }

  Future<void> _disconnect() async{
    await _room?.disconnect();
    await _room?.dispose();
  }

  Future<void> _reconnect() async {
    await _disconnect();
    await _requestToken(resume: true);
    _connect();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: _mainView(),
    );
  }

  Widget _mainView() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Obx(() {
            return Text(
              "${_seconds.value.toString()}s",
              style: Styles.textStyleSemiBold(30),
            );
          }),
          const SizedBox(height: 100),
          Obx(() {
            if (_token.value?.isNotEmpty == true) {
              return GestureContainer(
                onTap: () {
                  showTipsToast("on tap connect");
                  _connect();
                },
                color: Colors.greenAccent,
                child: Text(
                  "connect",
                  style: Styles.textStyleMedium(30),
                ),
              );
            }
            return const LoadingView();
          }),
          const SizedBox(height: 100),
          GestureContainer(
            onTap: () {
              showTipsToast("on tap reconnect");
              _reconnect();
            },
            color: Colors.greenAccent,
            child: Text(
              "reconnect",
              style: Styles.textStyleMedium(30),
            ),
          )
        ],
      ),
    );
  }
}
```
Attach Video:
https://github.com/user-attachments/assets/5ac6bb11-1a71-42d6-9d37-d90165dcef1f

If there are any suggestions or workarounds to address this issue, I would appreciate your guidance.
🎄 Merry Christmas! Wishing you a joyful holiday season! 🎄

**Comment by cloudwebrtc** [comment] 2024-12-27 02:26
hi, I copied this code, but I can't reproduce the issue. when you back to online, can you try to press the pause button in Xcode when the UI freezes and see the line of code blocked by the breakpoint? This may help us locate the line of code where the thread race occurs.

**Comment by ChungangL** [comment] 2024-12-27 05:57
OK. When the issue occurs, I pressed the pause button in Xcode, and the result is shown in the image. It seems to be related to the Visualizer class. Do you need any additional information?
![20241227-135343](https://github.com/user-attachments/assets/c4c94916-06d3-4084-80f9-899636d4c014)

**Comment by cloudwebrtc** [comment] 2024-12-27 06:21
okay I'm sure this issue has been fixed. Because of pod cache, your project has not been updated to this fix. You can try to delete your `app/ios/Podfile.lock`, `app/ios/Pods`, and use git dependencies to import `https://github.com/livekit/client-sdk-flutter` in `pubspec.yaml`. I will release a hot fix later so that you can fix it completely.

https://github.com/livekit/client-sdk-flutter/pull/667/files

**Comment by cloudwebrtc** [comment] 2024-12-27 06:39
done, please bump the version to 2.3.4.
https://pub.dev/packages/livekit_client/changelog

**Comment by ChungangL** [comment] 2024-12-27 08:32
It worked! Thank you so much!

**Comment by ChungangL** [comment] 2024-12-27 09:29
Hi @cloudwebrtc , Sorry to bother you again. An additional issue: After upgrading to version 2.3.4, during calls with AI on iOS devices, after ending a few calls and starting a new one, even if the `_preferSpeakerOutput` in the `Hardware` class is set to false, the `setSpeakerOn()` method cannot switch to the speaker, and the audio always comes through the earpiece.

**Comment by cloudwebrtc** [comment] 2024-12-30 03:46
I'm investigating, this seems to be related to iOS 18, I also reproduced this issue.

**Comment by cloudwebrtc** [comment] 2024-12-30 04:20
The good news is that I have fixed it, but I am verifying that the speaker can be switched correctly in normal mode and byPassVoiceProcessing. It will be fixed in a few minutes.

**Comment by ChungangL** [comment] 2024-12-30 07:02
> The good news is that I have fixed it, but I am verifying that the speaker can be switched correctly in normal mode and byPassVoiceProcessing. It will be fixed in a few minutes.

Do you have plans to release a new version？

**Comment by cloudwebrtc** [comment] 2024-12-30 08:00
@ChungangL fixed https://github.com/livekit/client-sdk-flutter/pull/672

**Closed** 2024-12-30 08:15 UTC

**Comment by cloudwebrtc** [comment] 2024-12-30 09:22
@furkanKotic I think this parameter no longer affect the connection of airpods. No matter whether you are using the handset or the speakerphone, the airpods will automatically route the airpods after connection. After disconnecting the airpods, return to the previous audio route

**Comment by ChungangL** [comment] 2024-12-31 04:22
Hello @cloudwebrtc , I tested the new version you released and found that the issue might originate from a previous commit. The stop() method is being called twice, and both times didStop is true, causing _remoteTrackCount in audio_management to become negative. This, in turn, affects the switching of the speaker.

Commit: 2afc9963969ccd8465cf583279015ceb01e87fec

![截屏2024-12-31 12 13 15](https://github.com/user-attachments/assets/c951bbbf-7927-4a2c-a0e7-b3f4b2c15281)
![截屏2024-12-31 12 21 26](https://github.com/user-attachments/assets/d7d38a7f-9b14-42b0-9f58-21737a3c5579)

**Comment by cloudwebrtc** [comment] 2024-12-31 05:46
Ah, thanks for finding it. Just created a fix https://github.com/livekit/client-sdk-flutter/pull/675
