### ISSUE TITLE
[bug] java.lang.NoClassDefFoundError - uf

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#236] opened 2023-01-27 07:46 UTC
**Describe the bug**
The new error in the last update is as follows in my Firebase log :

```
Fatal Exception: java.lang.NoClassDefFoundError: uf
       at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.java)
       at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.java)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.lambda$start$2(AudioSwitchManager.java)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.$r8$lambda$FuGFKeLXcL0hP6ArT3XVyqV-h6Q(AudioSwitchManager.java)
       at com.cloudwebrtc.webrtc.audio.AudioSwitchManager$$InternalSyntheticLambda$1$8bd2fe458ab16bc8551183726fbfff9127c94d3cf4c83549d207771a29a666f1$0.run(AudioSwitchManager.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6918)
```
**The error occurred in Android 5 version on Samsung phones.**

**Platform information**

* **Flutter version**: 
Flutter version 3.3.10 
* **Plugin version**:
livekit_client: ^1.1.12

**Comment by cloudwebrtc** [comment] 2023-01-31 04:49
Looks like a null object when operating asynchronously, this might be a useful fix.
https://github.com/flutter-webrtc/flutter-webrtc/pull/1246

**Comment by njovy** [comment] 2023-02-11 11:05
I am still getting this with flutter webrtc 0.9.21
```
java.lang.NoClassDefFoundError: com.twilio.audioswitch.scanners.AudioDeviceScanner
                                                                                                    	at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:87)
                                                                                                    	at com.twilio.audioswitch.AudioSwitch.<init>(AudioSwitch.kt:53)
                                                                                                    	at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.lambda$initAudioSwitch$2$com-cloudwebrtc-webrtc-audio-AudioSwitchManager(AudioSwitchManager.java:68)
                                                                                                    	at com.cloudwebrtc.webrtc.audio.AudioSwitchManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:135)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by cloudwebrtc** [comment] 2023-02-27 08:27
After investigation reproduced this issue on an Android 5.0 emulator., AudioSwitch does not support `Build.VERSION_CODES.M` below API Level 23, so (an Android 6.0) or above device is the minimum requirement (unless someone makes more versions of AudioDeviceScanner), I will close this issue.
<img width="936" alt="image" src="https://user-images.githubusercontent.com/17733746/221510355-d81b2893-b50c-405d-a531-5b98563f4a8e.png">

**Closed by cloudwebrtc** 2023-02-27 08:27 UTC
Labels: bug

**Comment by cloudwebrtc** [comment] 2023-02-27 08:29
I will increase the minimum android version requirement to API 23
